try{
  //例外が発生する可能性のあるコード
  notFunction()
} catch(error) {
  console.log('---output error---')
  
}